- name: Create BareMetalHost definition file for new worker
  copy:
    dest: "{{ scaling_dir }}/worker-{{ ansible_loop.index0 + scale_worker_index | int }}-bmh.yaml"
    content: |
      apiVersion: metal3.io/v1alpha1
      kind: BareMetalHost
      metadata:
        name: worker-{{ ansible_loop.index0 + scale_worker_index | int }}
        namespace: openshift-machine-api
      spec:
        online: true
        bmc:
          address: "ipmi://{{ item.pm_addr }}:623"
          credentialsName: "worker-{{ ansible_loop.index0 + scale_worker_index | int }}-bmc-secret"
        hardwareProfile: unknown
        bootMACAddress: "{{ item.prov_mac }}"
        userData:
          name: worker-user-data
          namespace: openshift-machine-api
  loop: "{{ scale_worker_node.nodes }}"
  loop_control:
    extended: yes

- name: Apply BareMetalHost for new worker
  environment:
    KUBECONFIG: "{{ kubeconfig_file }}"
  shell: |
    oc apply -f {{ scaling_dir }}/worker-{{ ansible_loop.index0 + scale_worker_index | int }}-bmh.yaml
  loop: "{{ scale_worker_node.nodes }}"
  loop_control:
    extended: yes

- name: wait for 600 seconds before checking for BareMetalHost state
  wait_for:
    timeout: 600

- name: Wait for BareMetalHost nodes to get into Ready state
  environment:
    KUBECONFIG: "{{ kubeconfig_file }}"
  shell: |
    oc -n openshift-machine-api get bmh/worker-{{ ansible_loop.index0 + scale_worker_index | int }} --template={{'{{'}}.status.provisioning.state{{'}}'}}
  register: bmh_node_ready
  retries: 30
  delay: 60
  until: bmh_node_ready.stdout.find("ready") != -1
  changed_when: bmh_node_ready.stdout_lines|length > 0
  loop: "{{ scale_worker_node.nodes }}"
  loop_control:
    extended: yes